from pytest import raises
from unittest.mock import MagicMock

from load_short_term import get_db_connection, load_all_data, create_dataframe
from load_short_term import add_availability_ids_to_sensor_df, add_botanist_ids_to_sensor_df, add_origin_ids_to_plant_df, add_plant_ids_to_sensor_df
from load_short_term import insert_dataframe_into_origin_table, insert_dataframe_into_plant_table
from load_short_term import insert_dataframe_into_sensor_result_table, insert_dataframe_into_botanist_table
